version: "3"

services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_PASSWORD: minhduy1
      POSTGRES_DB: rentalcar
    ports:
      - 5433:5433
    volumes:
      - database:/var/lib/postgresql/data
    tty: true
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - 80:80
    tty: true
    restart: always

volumes:
  database:
